### ISSUE TITLE
Normalize SST1 and SST2 to SST

### ISSUE THREAD

**Issue by danielballan** [NSLS2/nsls2api#12]
Background: It was agreed that, for data purposes, `sst` is a beamline but that `sst1`/`sst2` are not. I believe the reason is that a given endstation can take beam from one or the other or both at once, so it's simplest to just punt and call them both `sst`.

In PASS, there is a distinction, and proposals may be allocated to one or both. Currently, client code (e.g. https://github.com/NSLS2/proposal-directory-management) has to normalize this. The client code can be simplified if the server does this.

**Comment by JunAishima** [comment]
to clarify, the directory name should include `sst` only, for sst, sst1, and sst2?

**Comment by JunAishima** [comment]
Not sure if this is always the case, but I am generally finding that the directories in the proposal/xxx/directories endpoint always seemed to have "sst" in them.

**Comment by danielballan** [comment]
> to clarify, the directory name should include sst only, for sst, sst1, and sst2?

Yes.

**Comment by stuartcampbell** [comment]
This already works as expected.  Go and have a hard look at yourself in the mirror! 😄
