### ISSUE TITLE
Add endpoint to return a list of detectors for a given beamline

### ISSUE THREAD

**Issue by stuartcampbell** [NSLS2/nsls2api#19]
For example the detectors on `SRX` are

- bpmA_cam
- default
- dexela
- hfm_cam
- merlin
- xspress3
- zebra

@nmaytan Do we need to include the `default` in the list ?  i.e. is a real detector or just a catchall location ?

**Comment by nmaytan** [comment]
Yes, `default` is in our current list of managed directories for SRX assets. If we are "moving" this to proposals, I presume it should match - unless we take a line to only put detectors in assets.

**Comment by nmaytan** [comment]
I think the answer here is: not all assets dirs belong in the detector list, and therefore `default` should have a path entry but not be in the list of detectors
