### ISSUE TITLE
Add directory information for raw detector directories (i.e. assets)

### ISSUE THREAD

**Issue by stuartcampbell** [NSLS2/nsls2api#20]
The ACLs for the asset directories are currently:

assets-acls:
  - softioc-<tla>:rwx
  - workflows-<tla>:r-x
  - nsls2data:r-x
  - n2sn-dataadmin:r-x
  - n2sn-dataadmin-<tla>:r-x
  - pass-XXXXXX:r-x

**Comment by nmaytan** [comment]
For supreme clarity, the `softioc`, `workflows`, and second `dataadmin` should have `<tla>` appended.

**Comment by nmaytan** [comment]
We've [added test data](https://github.com/NSLS2/proposal-directory-management/blob/9c34752a380a4dcc99d64f037ea362359d9b565c/test_data/313507_subdirectories.json) of what we (hopefully) expect the response to look like for this endpoint (we called this `/beamline/<tla>/directories` for now). It matches the proposal directories structure exactly, only group_owner should not be hardcoded to `pass-XXXXXX` and this same group should not be in the groups list. The dir creation logic will default these to the relevant proposal group.

**Comment by stuartcampbell** [comment]
Ok - I was adding the `pass-XXXXXX` groups as it was in the list above, but I will revert it.  I've called the endpoint `/beamline/{name}/proposal-directory-skeleton/`.  I did have a {proposal_id} on the end so I could add the groups but will remove that.

**Comment by stuartcampbell** [comment]
As I mentioned (and agreed) with @danielballan yesterday -  the structure of both the proposal directories and this endpoint will change to include a key at the top level, so it will be 
```
{
  "directories" : [
     ... Same payload as before.
  ]
}
```

**Comment by nmaytan** [comment]
> Ok - I was adding the `pass-XXXXXX` groups as it was in the list above, but I will revert it. I've called the endpoint `/beamline/{name}/proposal-directory-skeleton/`. I did have a {proposal_id} on the end so I could add the groups but will remove that.

Yes, sorry for that. We realized during implementation that this information is not proposal-specific and therefore won't include proposal information- meaning it should be inferred during creation. That is, unless we duplicate it with a new endpoint for each proposal as mentioned.

We'll make adjustments to include the top-level key.

**Comment by stuartcampbell** [comment]
To clean up - do you ever use the `group_writable` field ? if not I am going to remove as the information is in the ACLs anyway and so if redundant

**Comment by nmaytan** [comment]
That field is unused on the script-side right now, and group-write is controlled totally by ACLs.
