### ISSUE TITLE
Add flag to indicate if the Year/Month/Day directory tree should be created for a given directory.

### ISSUE THREAD

**Issue by stuartcampbell** [NSLS2/nsls2api#32]

**Comment by stuartcampbell** [comment]
After some discussion on the PR #33 this has changed slightly to be an `enum` that contains the most granular level of directory we are going to create, e.g. `none|hour|day|month|year`.

**Comment by stuartcampbell** [comment]
@danielballan @nmaytan - as this is now configurable and not just a `bool`, I am presuming that we will have to store it per detector in the database ?

**Comment by stuartcampbell** [comment]
What should the default be for a detector that doesn't specify it ? `day` as we would do now ?

**Comment by stuartcampbell** [comment]
How does this look as a first try ?  Do you want to keep the boolean flag as well or not ? 

[response_1706912792451.json](https://github.com/NSLS2/nsls2api/files/14146084/response_1706912792451.json)

**Comment by nmaytan** [comment]
I like the simplicity of controlling this with one parameter, but I wonder if having the extra bool helps ease the configuration. I can't fully convince myself of how... I presume we would default this to off (so it doesn't apply to proposals/assets) and then set it in the detector database to retrieve per detector directory (will have to add to defaults too)
