### ISSUE TITLE
AMX/FMX/NYX lacking synchweb user right

### ISSUE THREAD

**Issue by JunAishima** [NSLS2/nsls2api#40]
In api-staging, the users list for the `proposal/??????/directories` endpoint contained 'synchweb': 'r', but this seems to have been lost for this endpoint, as well as the `beamline/??????/proposal-directory-skeleton`

**Comment by stuartcampbell** [comment]
Was that the correct behaviour ? What permissions do we want for synchweb ? Do they just need to be specified for the top level proposal directory or all the subdirs in the skeleton ? 

@danielballan @nmaytan thoughts ?

How do we know that a beamline is using synchweb ? Where should we configure this ?

**Comment by JunAishima** [comment]
There was a section in the old API code (https://github.com/NSLS-II/nsls2-api.git , api/proposal_api.py, line 243) where AMX, FMX, NYX, LiX had the 'synchweb': 'r' right added.

As far as I can see, this information is not stored anywhere explicitly, but the add_ispyb_db_users.yml playbook does have AMX, FMX, and NYX hosts that need to access the ISPyB database.

**Comment by danielballan** [comment]
Good catch, @JunAishima!

Since we were re-reviewing the security posture of these directories, I touched based with our ISO just to confirm that this is still a good approach. He agreed.

So, the goal is to get the same result we got before in terms of permissions on these directories. @stuartcampbell Let us know if you want any additional guidance on the implementation. Seems like you have it in hand.

**Comment by stuartcampbell** [comment]
Does this look correct ? 
[response_1707748517727.json](https://github.com/NSLS2/nsls2api/files/14239571/response_1707748517727.json)

**Comment by JunAishima** [comment]
> @JunAishima Does this look correct ? [response_1707748517727.json](https://github.com/NSLS2/nsls2api/files/14239571/response_1707748517727.json)

The synchweb right seems correct, but I think we had the lsdc-tla right available for LiX as well (hence I would have expected it in the first directory entry there).

This might give you a way to simplify this work - you could tie the synchweb right to lsdc-tla, if that is possible within the code.

**Comment by stuartcampbell** [comment]
Just looked at the database and LIX doesn't have a `lsdc` service account defined and so it shouldn't assign any permissions to that account
