### ISSUE TITLE
api-dev giving 500 failure when retrieving proposals for certain cycles

### ISSUE THREAD

**Issue by nmaytan** [NSLS2/nsls2api#43]
For example, 2016-1:

```
curl -X 'GET' \
  'https://api-dev.nsls2.bnl.gov/v1/facility/nsls2/cycle/2016-1/proposals' \
  -H 'accept: application/json'

500

Internal Server Error
```

**Comment by stuartcampbell** [comment]
I think that this is due to bad data for some of the proposals in certain cycles, which cause the Pydantic validation to fail.  I may need a little time to track down the bad data, but I don't think there will be any code changes.

**Comment by nmaytan** [comment]
Got it. I plan to run a test against all cycles, I will capture a complete list and share it here.

**Comment by nmaytan** [comment]
Update: coincidentally, 2016-1 is the only cycle that returns a 500. I tried against all cycles that the API lists All others seem to be fine.
