### ISSUE TITLE
cycles still being added to commissioning proposals

### ISSUE THREAD

**Issue by JunAishima** [NSLS2/nsls2api#52]
Getting the v1/proposal/314939 endpoint gives us a cycle of 2024-1, instead of being commissioning or empty. This makes its situation ambiguous - if we get the proposal through the list of all proposals for 2024-1, we may create the proposal directory under 2024-1, when in reality it should be in commissioning.

```
{
  "proposal": {
    "_id": "659c3ae640388984e964033f",
    "proposal_id": "314939",
    "data_session": "pass-314939",
    "title": "Routine Setup and Testing for Beamline 17‐ID‐2 ﴾FMX﴿",
    "type": "Beamline Commissioning (beamline staff only)",
    "pass_type_id": "300005",
    "instruments": [
      "FMX"
    ],
    "cycles": [
      "2024-1"
    ],
```

**Comment by nmaytan** [comment]
While I agree there is a larger conversation to be had about cycles being assigned to commissioning proposals en general, this is not really a problem as there is a `/proposals/commissioning` endpoint which we use as the final word on what is commissioning or not. See[ this line in the current PR](https://github.com/NSLS2/proposal-directory-management/blob/d0dd040f67c2da845bd902463152598ccd30aa32/create_proposal_directories.py#L668)

**Comment by stuartcampbell** [comment]
The commissioning proposals will still be 'measured' for the mentioned cycles, so I think it's still relevant to indicate which cycle the proposals are for.
