### ISSUE TITLE
Add new assets directories for BMM

### ISSUE THREAD

**Issue by nmaytan** [NSLS2/nsls2api#56]
Bruce would like to start using proposal-assets directories ahead of his data security beamtime, in part to improve the workflow for some intstruments that must write over Samba on Windows. This helped to solve a recent problem which nearly blocked an experiment (working together with @maatthias).

Bruce requests for now these two instruments for assets:

```
vsp300-1 <- biologic potentiostat
hpr20-1 <- hiden mass spectrometer
```

Both assets should be "flat" directories, i.e. without generating a YMDH tree.

**Comment by nmaytan** [comment]
Tagging @stuartcampbell for visibility, if you get a chance! :)

**Comment by stuartcampbell** [comment]
In our haste to do things at SRX, looks like I went to the trouble of creating a class `AssetDirectoryGranularity` that can have different levels, but then just hard coded the `directory_most_granular_level` to be `AssetDirectoryGranularity.day` 🤦 

I am assuming that we really want to 'attach' this to the "thing" (e.g. detector) that we are creating the directory for ?

**Comment by nmaytan** [comment]
Yes, that sounds right. Directory granularity should be a property of the instrument.

**Comment by nmaytan** [comment]
A more complete list for Bruce's instruments:
```
vsp300-1 <- biologic potentiostat
^ granularity = flat
hpr20-1 <- hiden mass spectrometer
^ granularity = flat
usbcam-1
^ granularity = YY/MM/DD
usbcam-2
^ granularity = YY/MM/DD
webcam-1
^ granularity = YY/MM/DD
webcam-2
^ granularity = YY/MM/DD
pilatus100k-1
^ granularity = YY/MM/DD
pilatus1m-2
^ granularity = YY/MM/DD
xspress3-1
^ granularity = YY/MM/DD
```
